[package]
name = "secret-attestation-token"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = []
sgx = ["serde/mesalock_sgx", "serde/sgx_tstd", "serde_json"] #

# Not sure if this can work without
[dependencies]
serde = { git = "https://github.com/mesalock-linux/serde-sgx", default-features = false, features = ["derive"] }
serde_json = { git = "https://github.com/mesalock-linux/serde-json-sgx", optional = true }
hex = "0.4.3"
base64 = "0.20.0"
